name: vaccine-management

services:
  ms-agendamento-db:
    image: postgres:latest
    restart: always
    networks:
      - vaccine-management-network
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: agendamento_db
    ports:
      - "5432:5432"

  ms-agendamento-api:
    image: ms-agendamento:latest
    build: ./ms-agendamento
    networks:
      - vaccine-management-network
    depends_on:
      - ms-agendamento-db
    ports:
      - "8091:8091"
    environment:
      SPRING_PROFILES_ACTIVE: prd
      SPRING_DATASOURCE_URL: jdbc:postgresql://ms-agendamento-db:5432/agendamento_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456

  ms-usuarios-db:
    image: postgres:latest
    restart: always
    networks:
      - vaccine-management-network
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: usuarios_db
    ports:
      - "5433:5432"

  ms-usuarios-api:
    image: ms-usuarios:latest
    build: ./ms-usuarios
    networks:
      - vaccine-management-network
    depends_on:
      - ms-usuarios-db
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ms-usuarios-db:5432/usuarios_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

networks:
  vaccine-management-network:
    driver: bridge