name: vaccine-management

services:
  ms-agendamento-db:
    image: postgres:latest
    restart: always
    networks:
      - vaccine-management-network
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: agendamento_db
    ports:
      - "5432:5432"

  ms-agendamento-api:
    image: ms-agendamento:latest
    build: ./ms-agendamento
    networks:
      - vaccine-management-network
    depends_on:
      - ms-agendamento-db
    ports:
      - "8091:8091"
    environment:
      SPRING_PROFILES_ACTIVE: prd
      SPRING_DATASOURCE_URL: jdbc:postgresql://ms-agendamento-db:5432/agendamento_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      MS_POSTO_HOST: ms-postos-vacina-api:8093
      MS_USUARIO_HOST: ms-usuarios-api:8082
      MS_VACINA_HOST: ms-vacina-api:8099

  ms-usuarios-db:
    image: postgres:latest
    restart: always
    networks:
      - vaccine-management-network
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: usuarios_db
    ports:
      - "5433:5432"

  ms-usuarios-api:
    image: ms-usuarios:latest
    build: ./ms-usuarios
    networks:
      - vaccine-management-network
    depends_on:
      - ms-usuarios-db
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ms-usuarios-db:5432/usuarios_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      MS_VACINA_HOST: ms-vacina-api:8099

  ms-vacina-api:
    image: ms-vacina:latest
    build: ./ms-vacina
    networks:
      - vaccine-management-network
    depends_on:
      - ms-vacina-db
    ports:
      - "8099:8099"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ms-vacina-db:5432/vacina_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456

  ms-vacina-db:
    image: postgres:latest
    restart: always
    networks:
      - vaccine-management-network
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: vacina_db
    ports:
      - "5434:5432"

  ms-postos-vacina-db:
    image: postgres:latest
    restart: always
    networks:
      - vaccine-management-network
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postos_vacina_db
    ports:
      - "5435:5432"

  ms-postos-vacina-api:
    image: ms-postos-vacina:latest
    build: ./ms-postos-vacina
    networks:
      - vaccine-management-network
    ports:
      - "8093:8093"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ms-postos-vacina-db:5432/postos_vacina_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456

networks:
  vaccine-management-network:
    driver: bridge