application:
  name: ms-usuarios

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ms_usuarios_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    jpa:
     defer-datasource-initialization: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgresql
      mode: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

ms-vacina:
  host: http://localhost:8081